# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
     
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - name: Checkout Dropzone
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

  # Auto tag when the package.json version has
  # changed. A different workflow will see this
  # tag, publish it, and create a release for it
  tag:
    runs-on: ubuntu-latest
    # This job depends on the test job, and
    # only runs on the master branch.
    if: github.ref == 'refs/heads/master'
    needs: [test]

    steps:
      - name: Checkout Dropzone
        uses: actions/checkout@v2
      - name: Auto tag
        uses: Klemensas/action-autotag@1.2.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: v
