# This workflow will build and push the website on the master branch
name: Build Website

on:
  push:
    branches: [ master ]
     
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - name: Checkout Dropzone
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-website
      - run: ls -la website
      - run: ls -la website/index.md
      - run: echo "foo" > website/index.md
      - run: ls -la website/
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: website
