# This workflow will build and push the website on the master branch
name: Build Website

on:
  push:
    branches: [ master ]
     
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
#       - name: Checkout Dropzone
#         uses: actions/checkout@v2
#       - run: rm website/.gitignore
#       - run: rm .gitignore
#       - run: npm install
      #- run: npm run build-website
      - run: mkdir website
      - run: echo "YEAH" > website/index.md
#       - run: ls -la website/
#       - run: ls -la website/index.md
#       - run: echo "FOOBAR" > website/index2.md
#       - run: cp website/index.md website/index3.md
#       - run: rm website/index.md
#       - run: cp website/index3.md website/index.md
#       - run: cp website/index3.md website/index.html
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: website
          #keep_history: true
