# This workflow will build and push the website on the master branch
name: Build Website

on:
  push:
    branches: [ master ]
     
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.1
      - name: Checkout Dropzone
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-website
      - run: ls -la website/
      - run: rm -rf website
      -
        name: Gen dummy page
        run: |
          mkdir website
          cat > website/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <title>GitHub Pages deployed!</title>
            </head>
            <body>
              <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
            </body>
          </html>
          EOL
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: website
